- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: create system user
  ansible.builtin.user:
    name: roboshop
    state: present
    comment: "roboshop system user"
    home: /app
    system: 'yes' # Set to 'yes' to create a system user with no home directory or shell by default

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent


- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory
      


- name: Delete user file
  ansible.builtin.file:
    path: /tmp/user.zip
    state: absent
      

- name: download user file to tmp directory
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip "
    dest: "/tmp/user.zip"

- name: extract user file to app direcory
  ansible.builtin.unarchive:
    src: /tmp/user.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    name: npm
    path: /app
    state: present
    
- name: copy user service
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service


- name: Start and enable user service
  ansible.builtin.systemd_service:
    name: user
    state: restarted
    enabled: yes
    daemon_reload: yes
  