- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: create system user
  ansible.builtin.user:
    name: roboshop
    state: present
    comment: "roboshop system user"
    home: /app
    system: 'yes' # Set to 'yes' to create a system user with no home directory or shell by default

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent


- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory
      


- name: Delete catalogue file
  ansible.builtin.file:
    path: /tmp/catalogue.zip
    state: absent
      

- name: download catalogue file to tmp directory
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip "
    dest: "/tmp/catalogue.zip"

- name: extract catalogue file to app direcory
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    name: npm
    path: /app
    state: present
    
- name: copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
    
- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh mongodb.sniggie.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

# - name: evaluate catalogue database
#   community.mongodb.mongodb_shell:
#     login_host: mongodb.daws86s.fun
#     eval: db.getMongo().getDBNames().indexOf('catalogue')
#   register: catalogue_output

# - name: print catalogue output
#   ansible.builtin.debug:
#     msg: "{{ catalogue_output }}"

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host mongodb.sniggie.fun </app/db/master-data.js
  when: catalogue_output.stdout | int < 0


- name: Start and enable catalogue service
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
  